apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-frontend-config
  labels:
    app.kubernetes.io/name: todo-frontend
data:
  config.json: |
    {
      "auth0Domain": "PLACEHOLDER",
      "auth0ClientId": "PLACEHOLDER",
      "auth0Audience": "PLACEHOLDER",
      "apiBaseUrl": "/api"
    }
