apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/enable-real-ip: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: PLACEHOLDER
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-backend
                port:
                  name: http
          - path: /q
            pathType: Prefix
            backend:
              service:
                name: todo-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-frontend
                port:
                  name: http
