apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-staging

resources:
  - ../../base

patches:
  - target: { kind: Namespace, name: PLACEHOLDER }
    patch: |-
      - op: replace
        path: /metadata/name
        value: todo-staging
  - target: { kind: Ingress, name: todo-app }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: todo.p-info.net
  - target: { kind: ConfigMap, name: todo-frontend-config }
    patch: |-
      - op: replace
        path: /data/config.json
        value: |
          {
            "auth0Domain": "pinfo.us.auth0.com",
            "auth0ClientId": "Km8ICah8B4Wo6F0J1uo0fKUGvuFcM7uQ",
            "auth0Audience": "https://todo-api.local",
            "apiBaseUrl": "/api"
          }
  - target: { kind: SecretProviderClass, name: todo-backend-secrets }
    patch: |-
      - op: replace
        path: /spec/parameters/clientID
        value: 6e185919-c495-44fb-aafe-981e01a57e04
      - op: replace
        path: /spec/parameters/keyvaultName
        value: kv-todo-staging
      - op: replace
        path: /spec/parameters/tenantId
        value: 20135588-0038-4e9b-b8bb-5684139f119b
  - target: { kind: ServiceAccount, name: todo-backend }
    patch: |-
      - op: replace
        path: /metadata/annotations/azure.workload.identity~1client-id
        value: 6e185919-c495-44fb-aafe-981e01a57e04

replicas:
  - name: todo-backend
    count: 1
  - name: todo-frontend
    count: 1

images:
  - name: todo-backend
    newName: acrtodoapphostettler.azurecr.io/todo-backend
    newTag: placeholder
  - name: todo-frontend
    newName: acrtodoapphostettler.azurecr.io/todo-frontend
    newTag: placeholder
